---
apiVersion: v1
kind: Service
metadata:
  name: {{.WORKFLOW_UI_NAME}}
  labels:
    name: {{.WORKFLOW_UI_NAME}}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    name: {{.WORKFLOW_UI_NAME}}
